gatsby-config.js, package.json, src/content/jokes.mdx, src/pages/404.js, yarn.lock
=> Added original content to 404 page

gatsby-config.js, package.json, yarn.lock
Complete end-to-end gatsby airtable configuration.
=> Added env configuration and gatsby airtable configuration

gatsby-config.js, package.json, yarn.lock
Initial s3 deployment configuration before ci/cd integration.
=> Added s3-deployment configuration

src/components/RestaurantThumb/index.js
=> Fix restaurant list when a restaurant don't have a thumbnail

gatsby-config.js, src/assets/styles/includes.scss, src/assets/styles/main.scss, src/assets/styles/mixins.scss, src/assets/styles/variables.scss
this PR just added the include paths to sass config
e fiz a small bug grid-custom-column mixin
=> Fix imports to scss files in the sma folder of component

buildspec.yml
First attempt to setup ci/cd inside the environment.
=> Adding buildspec file to config ci/cd for the project

src/assets/styles/main.scss, src/assets/styles/mixins.scss, src/assets/styles/variables.scss, src/components/RestaurantList/index.js, src/components/RestaurantList/styles.module.scss, src/components/RestaurantThumb/index.js, src/components/RestaurantThumb/styles.module.scss, src/pages/index.js
this PR added the first styles for restaurants list
=> Feature restaurants list

gatsby-node.js, src/components/Footer/index.js, src/components/HomeHeader/index.js, src/components/RestaurantThumb/index.js, src/helpers/index.js, src/templates/restaurant.js, yarn.lock
The basic page generation was added as a boilerplate before internal page creation.
=> This PR adds gatsby page generation routine for each restaurant

src/assets/styles/components/homeheader.modules.scss, src/assets/styles/main.scss, src/assets/styles/variables.scss, src/components/Header/styles.module.scss, src/components/RestaurantList/styles.module.scss, src/components/RestaurantThumb/index.js, src/components/RestaurantThumb/styles.module.scss
Changed the html font-size to be `62.5%` in order to get `1rem = 10px`, and changed the body font-size so it would scale if the user has a different font-size set in their browser, being more accessible. - b7d8e7e 
Added a safety check to prevent errors in case of an empty object in RestaurantThumb - e90d756
=> Change body/html font-size to be accessible and maintain ration.

src/assets/styles/variables.scss, src/components/Header/index.js, src/components/Header/styles.module.scss, src/components/RestaurantList/styles.module.scss
just fix mobile header with new sizes
=> Adjusted header to mobile

src/components/RestaurantOptions/index.js
Trying to avoid the user generated content breaking the build in
development environment.
=> Adding some default values to RestaurantOptions component

gatsby-node.js, src/components/RestaurantOptions/index.js, src/templates/Restaurant/index.js
Wrong selection of field (Telefone_para_Pedidos), typo error.
=> Bug fix inserting the phone correctly (Telefone_para_Pedidos)

src/components/RestaurantOptions/index.js
Trying to avoid future errors in user generated content.
=> Adding try/catch structure to avoid futute errors in UGC

package.json, src/assets/styles/main.scss, src/assets/styles/variables.scss, src/components/Header/index.js, src/components/Header/styles.module.scss, src/components/RestaurantHeader/index.js, src/components/RestaurantHeader/styles.module.scss, src/components/RestaurantList/styles.module.scss, src/components/RestaurantOptions/Button.js, src/components/RestaurantOptions/OptionButton.js, src/components/RestaurantOptions/index.js, src/components/RestaurantOptions/styles.module.scss, src/components/RestaurantThumb/styles.module.scss, src/hooks/useTheme.js, src/pages/index.js, src/templates/Restaurant/index.js, src/templates/Restaurant/styles.module.scss, src/utils/theming.js, yarn.lock
c98f3c6 - Display multiple categories in restaurant page
065db3a - Fix null values inside RestaurantOptions
b1ef5b1 - Fix RestaurantOptions links without restaurant name
2d6d9b6 - Prevent RestaurantOption button without content
b661edd - Add link opening to new tab
779cd26 - Implement theme logic
5266cf0 - Change Header logo to use Link instead of <a>
ba2608c - Add `window-or-global` package to deal with server side rending issues when accessing window
=> Restaurant page updates and theme logic

package.json, src/components/RestaurantOptions/Button.js, src/components/RestaurantOptions/OptionButton.js, src/components/RestaurantOptions/index.js, src/components/RestaurantOptions/styles.module.scss, yarn.lock
511fb11 - Add custom background based on the option
cce8035  - Set the RestaurantOptions order
=> Customize RestaurantOptions buttons

src/assets/styles/mixins.scss, src/components/RestaurantThumb/index.js, src/components/RestaurantThumb/styles.module.scss
this PR just adjusted the restaurant list to new layout
=> Adjusted restaurant list

src/components/CategoryFilter/index.js, src/components/FAQContent/index.js, src/components/Header/index.js, src/components/LocationFilter/index.js, src/components/RestaurantHeader/index.js, src/components/RestaurantList/index.js, src/templates/Restaurant/index.js, src/utils/theming.js
Some new category broke the build (missing category image).
=> Some lint removal and a category information breaking the build

src/pages/faq.js
Layout was written with lower case.
=> Layout import case sensitive correction

src/components/Header/index.js, src/components/Header/styles.module.scss
Including FAQ button  into Header component
=> New FAQ buttom

src/components/FAQContent/index.js
=> Adding target blank

src/components/Footer/index.js, src/components/Footer/styles.module.scss
=> add mailto

src/components/PageNotFoundContent/index.js, src/components/PageNotFoundContent/styles.module.scss, src/pages/404.js
=> 404 content

gatsby-config.js, package.json
=> Google analytics plugin

src/components/404Page/index.js
=> changing theme

src/templates/Restaurant/styles.module.scss
=> Changing bottom property

src/components/RestaurantThumb/index.js
=> Remove category lower case

src/utils/theming.js
Changing Padaria theme to get coffe theme
=> Changing Padaria theme

gatsby-config.js
Including url and image to metadata info
=> Updating metadata

src/components/RestaurantThumb/styles.module.scss
Changing restaurant category font size to 1.2 for mobile
=> Changing restaurant category font size

gatsby-node.js, src/components/RestaurantThumb/index.js, src/templates/Restaurant/index.js, yarn.lock
Now the system loads the "large" option for each file, generated
from airtable API.
=> Changed image gathering from Airtable to avoid load raw images

src/templates/Restaurant/index.js
Removing some pictures without large thumb version.
=> Omitting some pictures without large thumbnail version

src/components/FAQContent/styles.module.scss
=> Inserting underline

gatsby-config.js
=> Description change (new estabilishment types)

buildspec.yml
Fixing build system waiting for the final configuration for the
CI/CD.
=> Removing deprecated --acl public-read breaking the build

gatsby-config.js, src/components/Footer/index.js, src/components/Header/index.js, src/components/Home/index.js, src/components/HomeHeader/index.js
Some references to old brand updated.
=> Added new brand identity to the project
